apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.backend.service }}
  namespace: {{ .Values.namespace.name }}
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ports:
  - nodePort: {{ .Values.deployment.backend.nodePort }}
    port: {{ .Values.deployment.backend.port }}
    protocol: TCP
    targetPort: {{ .Values.deployment.backend.port }}
  selector:
    app: {{ .Values.labels.name }}
    tier: {{ .Values.labels.backend.tier }}
  type: NodePort
status:
  loadBalancer: {}
