apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.frontend.service }}
  namespace: {{ .Values.namespace.name }}
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ports:
  - port: {{ .Values.deployment.frontend.port }}
    protocol: TCP
    targetPort: {{ .Values.deployment.frontend.port }}
  selector:
    app: {{ .Values.labels.name }}
    tier: {{ .Values.labels.frontend.tier }}
  type: NodePort
status:
  loadBalancer: {}
