apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.Y2lsaXN0LXNlY3JldA }}
  namespace: {{ .Values.namespace.name }}
type: Opaque
data:
  DB_USER: cm9vdA==
  DB_PASS: cGFzc3dvcmQ=
  DB_SELECT: cGVvcGxl
  DB_ENDPOINT: Y2lsaXN0LWRiLmNhaDR6ZW9kdXZpMi51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20=
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
